name: Build and Deploy to Netlify
on: [push]

jobs:
  dependency-installation:
    name: Install Deps
    runs-on: ubuntu-latest
    steps:

    - name: Install Machine Deps
      uses: actions/setup-node@v3
      with:
          node-version: 18.15


  build-project:
    needs: dependency-installation
    name: Build Project
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm i
    
    - name: Build Project
      run: npm run build

    - name: Cache Builds
      uses: actions/cache@v2.1.8
      with:
        path: |
          ./node_modules
          ./build
          ${{ steps.node-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}


  webpage-deploy:
    if: ${{ always() }}
    needs: [dependency-installation, build-project]
    name: Deploy Webpage
    runs-on: ubuntu-latest
    environment: production
    steps:

    - uses: actions/checkout@v3

    - name: Cache Restore
      uses: ylemkimon/cache-restore@v2.1.3
      with:
        path: |
          ./node_modules
          ./build
        restore-keys: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: Deploy Webpage with Netlify
      uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: './build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        if: ${{ failure() }}
  
  
  list-files:
    needs: [dependency-installation, build-project]
    name: List Files
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
          path: "./"

      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done