name: Build and Deploy to Netlify
on: [push]

jobs:
  dependency-installation:
    name: Install Deps
    runs-on: ubuntu-latest
    steps:

#   Install Machine Deps
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.15


  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
#   Install Project Deps
    - run: npm i
    - run: npm run build


  webpage-deploy:
    name: Deploy Webpage
    runs-on: ubuntu-latest
    environment: production
    steps:

#   Deploy Webpage with Netlify
    - uses: nwtgck/actions-netlify@v2.0.0
      with:
        publish-dir: './build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1